# CountrySelect
module ActionView
  module Helpers
    module FormOptionsHelper
      # Return select and option tags for the given object and method, using country_options_for_select to generate the list of option tags.
      def country_select(object, method, priority_countries = nil, options = {}, html_options = {})
        InstanceTag.new(object, method, self, options.delete(:object)).to_country_select_tag(priority_countries, options, html_options)
      end
      # Returns a string of option tags for pretty much any country in the world. Supply a country name as +selected+ to
      # have it marked as the selected option tag. You can also supply an array of countries as +priority_countries+, so
      # that they will be listed above the rest of the (long) list.
      #
      # NOTE: Only the option tags are returned, you have to wrap this call in a regular HTML select tag.
      def country_options_for_select(selected = nil, priority_countries = nil)
        country_options = ""

        if priority_countries
          country_options += options_for_select(priority_countries, selected)
          country_options += "<option value=\"\" disabled=\"disabled\">-------------</option>\n"
        end

        return country_options + options_for_select(COUNTRIES, selected)
      end
      # All the countries included in the country_options output.
      #
      COUNTRIES = ["Andorra",
        "Emirados Árabes Unidos",
        "Afeganistão",
        "Antígua e Barbuda",
        "Anguilla",
        "Albânia",
        "Armênia",
        "Antilhas Holandesas",
        "Angola",
        "Antártida",
        "Argentina",
        "Samoa Americana",
        "Áustria",
        "Austrália",
        "Aruba",
        "Ilhas Aland",
        "Azerbaijão",
        "Bósnia-Herzegovina",
        "Barbados",
        "Bangladesh",
        "Bélgica",
        "Burquina Faso",
        "Bulgária",
        "Bahrain",
        "Burundi",
        "Benin",
        "São Bartolomeu",
        "Bermudas",
        "Brunei",
        "Bolívia",
        "Brasil",
        "Bahamas",
        "Butão",
        "Ilha Bouvet",
        "Botsuana",
        "Belarus",
        "Belize",
        "Canadá",
        "Ilhas Coco",
        "Congo-Kinshasa",
        "República Centro-Africana",
        "Congo",
        "Suíça",
        "Costa do Marfim",
        "Ilhas Cook",
        "Chile",
        "República dos Camarões",
        "China",
        "Colômbia",
        "Costa Rica",
        "Sérvia e Montenegro",
        "Cuba",
        "Cabo Verde",
        "Ilhas Natal",
        "Chipre",
        "República Tcheca",
        "Alemanha",
        "Djibuti",
        "Dinamarca",
        "Dominica",
        "República Dominicana",
        "Argélia",
        "Equador",
        "Estônia",
        "Egito",
        "Saara Ocidental",
        "Eritreia",
        "Espanha",
        "Etiópia",
        "Finlândia",
        "Fiji",
        "Ilhas Malvinas",
        "Micronésia",
        "Ilhas Faroe",
        "França",
        "Gabão",
        "Reino Unido",
        "Granada",
        "Geórgia",
        "Guiana Francesa",
        "Guernsey",
        "Gana",
        "Gibraltar",
        "Groênlandia",
        "Gâmbia",
        "Guiné",
        "Guadalupe",
        "Guiné Equatorial",
        "Grécia",
        "Geórgia do Sul e Ilhas Sandwich do Sul",
        "Guatemala",
        "Guam",
        "Guiné Bissau",
        "Guiana",
        "Hong Kong, Região Admin. Especial da China",
        "Hong Kong",
        "Ilha Heard e Ilhas McDonald",
        "Honduras",
        "Croácia",
        "Haiti",
        "Hungria",
        "Indonésia",
        "Irlanda",
        "Israel",
        "Ilha de Man",
        "Índia",
        "Território Britânico do Oceano Índico",
        "Iraque",
        "Irã",
        "Islândia",
        "Itália",
        "Jersey",
        "Jamaica",
        "Jordânia",
        "Japão",
        "Quênia",
        "Quirguistão",
        "Camboja",
        "Quiribati",
        "Comores",
        "São Cristovão e Nevis",
        "Coreia do Norte",
        "Coreia do Sul",
        "Kuwait",
        "Ilhas Caiman",
        "Casaquistão",
        "República Popular Democrática do Laos",
        "Líbano",
        "Santa Lúcia",
        "Liechtenstein",
        "Sri Lanka",
        "Libéria",
        "Lesoto",
        "Lituânia",
        "Luxemburgo",
        "Letônia",
        "Líbia",
        "Marrocos",
        "Mônaco",
        "Moldávia",
        "Montenegro",
        "São Martinho",
        "Madagascar",
        "Ilhas Marshall",
        "Macedônia",
        "Mali",
        "Mianmar",
        "Mongólia",
        "Macau, Região Admin. Especial da China",
        "Macau",
        "Ilhas Marianas do Norte",
        "Martinica",
        "Mauritânia",
        "Montserrat",
        "Malta",
        "Maurício",
        "Maldivas",
        "Malawi",
        "México",
        "Malásia",
        "Moçambique",
        "Namíbia",
        "Nova Caledônia",
        "Níger",
        "Ilha Norfolk",
        "Nigéria",
        "Nicarágua",
        "Holanda",
        "Noruega",
        "Nepal",
        "Nauru",
        "Niue",
        "Nova Zelândia",
        "Omã",
        "Panamá",
        "Peru",
        "Polinésia Francesa",
        "Papua-Nova Guiné",
        "Filipinas",
        "Paquistão",
        "Polônia",
        "Saint Pierre e Miquelon",
        "Pitcairn",
        "Porto Rico",
        "Território da Palestina",
        "Portugal",
        "Palau",
        "Paraguai",
        "Catar",
        "Oceania Remota",
        "União Europeia",
        "Reunião",
        "Romênia",
        "Sérvia",
        "Rússia",
        "Ruanda",
        "Arábia Saudita",
        "Ilhas Salomão",
        "Seychelles",
        "Sudão",
        "Suécia",
        "Cingapura",
        "Santa Helena",
        "Eslovênia",
        "Svalbard e Jan Mayen",
        "Eslováquia",
        "Serra Leoa",
        "San Marino",
        "Senegal",
        "Somália",
        "Suriname",
        "São Tomé e Príncipe",
        "El Salvador",
        "Síria",
        "Suazilândia",
        "Ilhas Turks e Caicos",
        "Chade",
        "Territórios Franceses do Sul",
        "Togo",
        "Tailândia",
        "Tadjiquistão",
        "Tokelau",
        "Timor Leste",
        "Turcomenistão",
        "Tunísia",
        "Tonga",
        "Turquia",
        "Trinidad e Tobago",
        "Tuvalu",
        "Taiwan",
        "Tanzânia",
        "Ucrânia",
        "Uganda",
        "Ilhas Menores Distantes dos Estados Unidos",
        "Estados Unidos",
        "Uruguai",
        "Uzbequistão",
        "Vaticano",
        "São Vicente e Granadinas",
        "Venezuela",
        "Ilhas Virgens Britânicas",
        "Ilhas Virgens dos EUA",
        "Vietnã",
        "Vanuatu",
        "Wallis e Futuna",
        "Samoa",
        "Iêmen",
        "Mayotte",
        "África do Sul",
        "Zâmbia",
        "Zimbábue"] unless const_defined?("COUNTRIES")
    end
    
    class InstanceTag
      def to_country_select_tag(priority_countries, options, html_options)
        html_options = html_options.stringify_keys
        add_default_name_and_id(html_options)
        value = value(object)
        content_tag("select",
          add_options(
            country_options_for_select(value, priority_countries),
            options, value
          ), html_options
        )
      end
    end
    
    class FormBuilder
      def country_select(method, priority_countries = nil, options = {}, html_options = {})
        @template.country_select(@object_name, method, priority_countries, options.merge(:object => @object), html_options)
      end
    end
  end
end
